## ???  ?????
server:
  port: 8081
  servlet:
    context-path: /crs

## ?????
spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/car?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: cyx123456

  ## freemarker
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    template-loader-path: classpath:/views/

  ## ?????
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

## mybatis ??
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.yjxxt.crs.bean;com.yjxxt.crs.query;com.yjxxt.crs.dto
  configuration:
    map-underscore-to-camel-case: true

## pageHelper ??
pagehelper:
  helper-dialect: mysql

## ?? dao ??????
logging:
  level:
    com:
      yjxxt:
        crs:
          mapper: debug